name: CI

on: [pull_request]

jobs:
  build_and_test:
    name: Build and Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      # - name: Find latest rust stable version
      #   id: rust_stable_version
      #   run: |
      #     VER=$(curl -s https://static.rust-lang.org/dist/channel-rust-stable.toml | grep -A 1 "\[pkg\.rust\]" | grep version | sed -r 's/.*\"(.*)\".*/\1/')
      #     echo "$VER"
      #     echo "##[set-output name=rustc;]$VER"

      # - name: Cache rust toolchain
      #   id: cache_rust_toolchain
      #   uses: actions/cache@v1
      #   with:
      #     key: ${{ steps.rust_stable_version.outputs.rustc }}
      #     path: "~/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/"

      - name: Install stable toolchain
        if: steps.cache_rust_toolchain.output.cache-hit != 'true'
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          components: rustfmt, clippy
          override: true

      - name: Build
        uses: actions-rs/cargo@v1
        with:
          command: build

      - name: Test
        uses: actions-rs/cargo@v1
        with:
          command: test

      - name: Check formatting
        uses: actions-rs/cargo@v1
        with:
          command: fmt
          args: --all -- --check

      - name: Clippy
        uses: actions-rs/cargo@v1
        with:
          command: clippy
